# Generated by Django 2.2.2 on 2019-07-12 07:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaWeb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='fechaEmision',
        ),
        migrations.AddField(
            model_name='boleta',
            name='emision',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de Emisión'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especialidad',
            name='valor',
            field=models.IntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='horaAtencion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ClinicaWeb.HoraAtencion'),
        ),
    ]
