# Generated by Django 2.2.2 on 2019-07-12 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClinicaWeb', '0003_auto_20190712_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horaatencion',
            name='horaAtencion',
            field=models.CharField(choices=[('09:00', '09:00'), ('09:30', '09:30'), ('10:00', '10:00'), ('10:30', '10:30'), ('11:00', '11:00'), ('11:30', '11:30'), ('12:00', '12:00'), ('12:30', '12:30'), ('13:00', '13:00'), ('13:30', '13:30'), ('14:00', '14:00'), ('14:30', '14:30'), ('15:00', '15:00'), ('15:30', '15:30'), ('16:00', '16:00'), ('16:30', '16:30'), ('17:00', '17:00'), ('17:30', '17:30'), ('18:00', '18:00'), ('18:30', '18:30'), ('19:00', '19:00'), ('19:30', '19:30'), ('20:00', '20:00')], default='09:00', max_length=5),
        ),
    ]
